/**
 * Runs the scenario seed-search and writes the committed fixture
 * `tools/fixtures/scenarios.json`, plus a readable summary table to the console.
 *
 * Usage:  pnpm --filter @sauda/tools scenarios [maxSeed]   (default 2000)
 *
 * The fixture is the cache the brief asks for: any future session (or the capture dev route)
 * can jump straight to a state by replaying its recorded action log — no re-search needed.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { searchScenarios, SCENARIO_IDS } from './scenarios';

const maxSeed = Number(process.argv[2] ?? 2000);
const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(here, '../fixtures/scenarios.json');

console.log(`Searching seeds 1..${maxSeed} for ${SCENARIO_IDS.length} target states…\n`);
const results = searchScenarios(maxSeed);

// Console summary — state · seed · turn · steps-to-replay · found/NOT FOUND.
let foundCount = 0;
for (const id of SCENARIO_IDS) {
  const outcome = results[id]!;
  if (outcome.found) {
    foundCount += 1;
    console.log(`  ${id.padEnd(18)} seed ${String(outcome.seed).padStart(5)}  turn ${String(outcome.turn).padStart(3)}  (${outcome.actions.length} steps)`);
  } else {
    console.log(`  ${id.padEnd(18)} NOT FOUND (searched ${outcome.searched} seeds)`);
  }
}
console.log(`\n${foundCount}/${SCENARIO_IDS.length} states found.`);

const fixture = {
  note: 'Deterministic Phase-B capture states. Replay `actions` into the store (via dispatch) after newGame(seed) with seats [human, bot, bot, bot] to land the real UI on each state. Generated by tools/src/find-scenarios.ts — do not hand-edit.',
  seatCount: 4,
  maxSeedSearched: maxSeed,
  states: results,
};

mkdirSync(dirname(fixturePath), { recursive: true });
writeFileSync(fixturePath, JSON.stringify(fixture, null, 2) + '\n');
console.log(`\nWrote ${fixturePath}`);
